[package]
name = "buckets"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
once_cell = "1.20.2"
log = "0.4.22"
duckdb = "1.1.1"
tempfile = "3.13.0"
assert_cmd = "2.0.16"
