[package]
name = "buckets"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
once_cell = "1.20.2"
log = "0.4.22"
duckdb = { version = "1.1.1", features = ["bundled"] }
tempfile = "3.13.0"
assert_cmd = "2.0.16"
toml = "0.8.19"
serde = { version = "1.0.215", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }
serde_derive = "1.0.215"
blake3 = "1.5.5"
walkdir = "2.5.0"
chrono = "0.4.38"
predicates = "3.1.2"
