name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
            
      - name: Build and Test
        run: |
          cargo build --release --all-features
          cargo test --release
          
      - name: Install Tarpaulin
        run: |
          cargo install cargo-tarpaulin
        
      - name: Run Tests with Coverage
        run: |
         cargo tarpaulin --release --out Html --timeout 120
         mv tarpaulin-report.html coverage.html
         
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
         name: coverage-report
         path: coverage.html
